### ISSUE TITLE
Implement GET /users/:userID/projects/:projectID w/ tests

### ISSUE THREAD

**Issue by sedge** [mozilla/publish.webmaker.org#10]
Retrieve a single project object.

```js
{
  projects: ...
}
```

**Comment by gideonthomas** [comment]
We also want to capture the query string and if `?includeFiles=true` is passed in, include each file's buffer data in each file's object otherwise only return an array of fileIDs

**Comment by ashleygwilliams** [comment]
@gideonthomas i think the ?include=<linked_resource> should be it's own issue
