### ISSUE TITLE
ValidationError: `description` is not allowed to be empty

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/publish.webmaker.org#100]
We seem to not allow description to be an empty string for the project resource. I don't think this is such a good idea because from thimble's perspective, users might not want to give a description which should be fine.

**Comment by sedge** [comment]
We can change this to be an optional field.

**Comment by ashleygwilliams** [comment]
i don't see where this would be happening:
- migration: http://popehat.com/2015/06/10/two-kinds-of-freedom-of-speech-or-strangeloop-vs-curtis-yarvin/
- schema: https://github.com/mozilla/publish.webmaker.org/blob/master/api/modules/projects/schema.js#L8

**Comment by ashleygwilliams** [comment]
@gideonthomas can you give a more specific description of the use case where you see the error

**Comment by gideonthomas** [comment]
Try:
`curl -X PUT -H "Content-Type: application/json" -d '{"user_id": 1, "title": "spacecats-API", "tags": "sinatra, api, REST, server, ruby", "description": "", "date_created": "2015-06-03T13:21:58+00:00", "date_updated": "2015-06-03T13:21:58+00:00"}' http://localhost:2015/projects/1`

I get back an error that says:
`{"statusCode":400,"error":"Bad Request","message":"`id` invalid"}`

And in the `publish.webmaker.org` console I see the following error:
```js
{
      "data": {
        "name": "ValidationError",
        "details": [
          {
            "message": "\"description\" is not allowed to be empty",
            "path": "description",
            "type": "any.empty",
            "context": {
              "key": "description"
            }
          }
        ],
        "_object": {
          "user_id": 1,
          "title": "spacecats-API",
          "tags": "sinatra, api, REST, server, ruby",
          "description": "",
          "date_created": "2015-06-03T13:21:58+00:00",
          "date_updated": "2015-06-03T13:21:58+00:00"
        }
      },
      "isBoom": true,
      "isServer": false,
      "output": {
        "statusCode": 400,
        "payload": {
          "statusCode": 400,
          "error": "Bad Request",
          "message": "child \"description\" fails because [\"description\" is not allowed to be empty]",
          "validation": {
            "source": "payload",
            "keys": [
              "description"
            ]
          }
        },
        "headers": {}
      }
    }
```

**Comment by gideonthomas** [comment]
Here's where the problem is (look at the first line):
https://github.com/hapijs/joi#string

**Comment by sedge** [comment]
I'll whip up a patch real quick.

**Comment by sedge** [comment]
There's another bug that this surfaces, which is that the error is the same whether the payload or  parameter validation fails.
