### ISSUE TITLE
Enforce a file size limit

### ISSUE THREAD

**Issue by ashleygwilliams** [mozilla/publish.webmaker.org#101]
do we have a cap on the size of the file someone can upload? if we accept files > 5GB we will need to use multi-part uploads to put them on s3

see: https://forums.aws.amazon.com/message.jspa?messageID=326498

on multi-part uploads: http://docs.aws.amazon.com/AmazonS3/latest/dev/uploadobjusingmpu.html

fwiw, i am using the [node-s3-client](https://github.com/andrewrk/node-s3-client), which would help us seamlessly transition to multi-part uploads. this question is mostly for my own knowledge and also a consideration we might want to make, even if the implementation isn't prohibitive.

**Comment by humphd** [comment]
Currently we're capping file size for drag-and-drop into Brackets at 3M, so I think that staying under 5M is a fine idea.  We also discussed on Tuesday the need for us to move to multi-part uploads anyway, so this is all good.

**Comment by gideonthomas** [comment]
@ashleygwilliams you might want to follow https://github.com/mozilla/thimble.webmaker.org/issues/626 for any updates on this from the thimble front.
