### ISSUE TITLE
Support incremental DIFF file updates

### ISSUE THREAD

**Issue by humphd** [mozilla/publish.webmaker.org#11]
NOTE: This is an optimization I want to work toward, and I'm filing it now so that we can make sure that our data store + API designs are able to evolve in this direction.

I want to see us support both whole file uploads, as well as incremental diffs, where possible.  We've previously written the equivalent of rsync's rolling DIFF algorithm for the browser and node.  I want to leverage that code here, in order to allow file updates to be as small as possible, while we autosave on the client.  Here's how I imagine it working:

* user saves a file to the browser filesystem
* an md5sum is calculated for this file
* because it's the first time this file is being written, Thimble sends the entire file, along with the checksum.
* server receives entire file, and stores it, along with the checksum (it can recalculate it, if you want).
* user updates file, autosave occurs to the browser filesystem
* when the file is autosaved, browser sees that file exists already, creates a diff
* Thimble sends diff + checksum of last updated version of the file (i.e., what's saved to filesystem vs. what's currently *being* saved)
* server gets diff and checksum for file path.  It compares against the checksum it already has for the file, and if it matches, it applies the diff, updates the checksum, and saves the file.  If the checksum does not match, it fails the request, and asks the client to send the whole file.

This is a very conservative incremental update strategy.  It does not support multiple, simultaneous clients or attempt to deal with merge conflicts.  In every case where data corruption may occur, the full file contents are requested.  As such, in the worst case, this is no better than always sending the full file; however, in the best case, it means we are sending very small updates over and over during a user's editing session.

**Comment by gideonthomas** [comment]
Not something we are doing anytime soon, closing!
