### ISSUE TITLE
Error R14 (Memory quota exceeded) on prod

### ISSUE THREAD

**Issue by humphd** [mozilla/publish.webmaker.org#145]
I see a lot of this on Heroku logs:

```
Sep 03 12:25:06 publish-webmaker-org-prod heroku/web.4: Error R14 (Memory quota exceeded)
```

Would be good to figure out where we are leaking.

**Comment by ashleygwilliams** [comment]
node.js processes have a memory limit of around 1.4GB, which explains the crashes. i am investigating now.

**Comment by ashleygwilliams** [comment]
<img width="754" alt="screen shot 2015-09-09 at 6 08 19 pm" src="https://cloud.githubusercontent.com/assets/1163554/9775514/cd988860-571d-11e5-81f8-d900735784fd.png">
<img width="765" alt="screen shot 2015-09-09 at 6 08 08 pm" src="https://cloud.githubusercontent.com/assets/1163554/9775516/d24a3a3e-571d-11e5-91fd-1887a636d8a5.png">

**Comment by jbuck** [comment]
The R14 error doesn't mean that the process has crashed, simply that it's gone above the 512MB memory quota. Above 512MB it goes into swap, represented by the dark gray line at the bottom of the graph.

**Comment by ashleygwilliams** [comment]
@jbuck yeah, i guess i'm speaking more to what @humphd is observing as multiple crashes. do we have new relic data?

frankly, i don't think this is a leak. it doesn't have the classic "toothy" pattern leaks do- i.e. the consistent slope up then drop. these are spikes, so something is happening very rapidly. i'm still investigating, but wanted to share that.

**Comment by humphd** [comment]
Thanks for digging into this.  If we decide that this is normal behaviour, and not a leak (I think your points above are right on that front), then maybe we should be asking if it's wise to have this thing live at its memory capacity all the time, and be forced into swap so much?  I'm not sure.

**Comment by jbuck** [comment]
There are no dyno crashes happening - there are many [request timeouts](https://devcenter.heroku.com/articles/error-codes#h10-app-crashed) which would also return the error html.

No newrelic data afaik; probably worth adding newrelic to publish.

@humphd how heavily is the tar functionality used by thimble? It's only a hunch, but if we had to instrument a single section of the code, I bet we'd see some results instrumenting that.

I also switched the dynos to 2X dynos, which have 1GB of memory.

**Comment by humphd** [comment]
The tar functionality is used every time you open or remix a project, in order to send the entire filesystem image in a single request.  We use `tar-stream` to create this, but every tar implementation basically needs to assemble things in memory; so yes, I agree with you that instrumenting that bit might be really helpful.  cc @sedge, @gideonthomas, who wrote that code and could help us pinpoint it.

RE the increase to 1GB of memory, thank you.  I think that makes a lot of sense until we can teach this thing to live in smaller resourced servers.

**Comment by sedge** [comment]
A few thoughts off the top of my head:

* When we stream tar files from publish, the files themselves are [read into memory](https://github.com/mozilla/publish.webmaker.org/blob/45b3fe43d5345d640326226bee0325c19cfc05c2/api/classes/prerequisites.js#L9-L59) [first](https://github.com/mozilla/publish.webmaker.org/blob/45b3fe43d5345d640326226bee0325c19cfc05c2/api/modules/files/routes/read.js#L78-L82) before [the handler](https://github.com/mozilla/publish.webmaker.org/blob/45b3fe43d5345d640326226bee0325c19cfc05c2/api/classes/base_controller.js#L87) creating the tar-stream executes. Could that be a bottleneck with many users at once?
* There are some examples where we fetch models more than once in a request, like [in that same handler](https://github.com/mozilla/publish.webmaker.org/blob/45b3fe43d5345d640326226bee0325c19cfc05c2/api/classes/base_controller.js#L94-L102)

I'll take a closer look tomorrow to see if I can pin down other examples of this.

**Comment by ashleygwilliams** [comment]
the 2x dynos seem to have fixed this (note the distinct shift to no errors post at 12am last night)
<img width="770" alt="screen shot 2015-09-10 at 10 38 48 am" src="https://cloud.githubusercontent.com/assets/1163554/9791299/525f2df8-57a8-11e5-9a0f-e422f309b405.png">

**Comment by sedge** [comment]
@jbuck Since the dyno upgrade seems to have solved the problem, can we close?

**Comment by jbuck** [comment]
It's solved the immediate problem of going over the memory quota, but the server still uses an excessive amount of memory doing something (that needs to be measured), and there are still request timeouts happening.
