### ISSUE TITLE
Requests to id.webmaker.org take too long

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/publish.webmaker.org#153]
Based on various sets of newrelic data (an example below), we think that a lot of our request timeouts happening on the publish server are due to a very long response time from id.webmaker.org:
![screen shot 2015-09-15 at 12 57 59 pm](https://cloud.githubusercontent.com/assets/5816130/9884912/623915b6-5bb0-11e5-8792-9c5b5ca16e99.png)

We had a conversation on IRC about it:
```irc
13:08 humph: we're seeing timouts on the publish server, that look to be due to id
13:08 humph: i.e., timeouts with id
13:09 cade: might be the id -> login.wmo dependency
13:09 gthomas: -.-
13:10 cade: We've got fixing that on our roadmap
13:12 humph: can you expand on what the issue is?
13:12 humph: and timeline
13:15 humph: cade: ?
13:15 cade: id is basically using login.wmo as a user storage service, which is really slow and undesireable.
```

So we need to wait on id.wm.org to fix this issue and then investigate if we still have request timeouts.

**Comment by humphd** [comment]
cc @cadecairos, who seems to know about the issue, fix, and timeline.

**Comment by cadecairos** [comment]
I've added updating this ticket  to my personal to do list.

Once we finalize the roadmap and convert tasks to tickets, I'll be back!

**Comment by humphd** [comment]
<blockquote>Request timeouts. There have been 942 timeout errors in the last day. Try investigating slow requests, adding more dynos or running more processes per dyno.</blockquote>

Fixing this would be great, because it seems to happen a lot.  cc @hannahkane

**Comment by jbuck** [comment]
I think this will be improved by the get user caching patch @cadecairos wrote. Monitoring for a day to make sure though

**Comment by humphd** [comment]
This is *way* better:

![screenshot 2015-10-06 10 55 40](https://cloud.githubusercontent.com/assets/427398/10312346/dcfdf6e0-6c18-11e5-8662-01b45d077ae7.png)

The average being at 170ms is still pretty high, but not terrible.  I'm going to close this and we can file follow-up bugs if we decide to dig in further.
