### ISSUE TITLE
add CORS clearance to the entire app

### ISSUE THREAD

**Issue by Pomax** [mozilla/publish.webmaker.org#156]
when calling publish.wmo client side, all the not-GET routes are "locked down" due to a missing explicit `cors:true`. This should be relatively straight forward to add in, as HAPI allows the global server instance to be told whether or not to allow CORS.

**Comment by ashleygwilliams** [comment]
```
new Hapi.Server({
  connections: {
    routes: {
      cors: true
    }
  }
})
```
