### ISSUE TITLE
projects should be able to a "which tool built this project" field

### ISSUE THREAD

**Issue by Pomax** [mozilla/publish.webmaker.org#159]
Right now publish.wmo assume the publishing tool is always Thimble, however with work underway on Goggles, this will not stay true for long. An additional field to indicate which publishing tool was used to build a project will be quite valuable for filtering/gallery purposes.

**Comment by ashleygwilliams** [comment]
+1

**Comment by Pomax** [comment]
Do we want this to be mandatory, so that other tools can't pretend to be Thimble by leaving off their client name, or should we just make this "if you fill in a tool name, we can filter on it, otherwise whatever"?

**Comment by sedge** [comment]
I think "If you fill in a tool name we can filter it, otherwise whatever" is the smartest place to start.

**Comment by Pomax** [comment]
agreed
