### ISSUE TITLE
extend the project definition with a "locked" property to prevent remixing

### ISSUE THREAD

**Issue by Pomax** [mozilla/publish.webmaker.org#163]
If Goggles needs to use the publish.wmo approach, then its projects should not be remixable, which requires passing an extra optional argument `editable:false` (or similar flag) into the project creation call. These projects should be published without the remix code added, and should reasonably not be loaded up by tools that can edit projects (which right now is just thimble).

**Comment by sedge** [comment]
Why shouldn't goggles projects be remixable in thimble? Wouldn't that create a nice synergy between the tools if it was possible?

**Comment by Pomax** [comment]
Because not everyone shares those ideals. Especially not when someone remixes license-encumbered content and we then host that content. Until legal tells us we can actually allow remixing for arbitrary web content, this will have to do.
