### ISSUE TITLE
consider making project:date_created and project:date_updated implied for POST:/projects

### ISSUE THREAD

**Issue by Pomax** [mozilla/publish.webmaker.org#165]
When creating a new project, the current scheme requires specifying a creation and update timestamp, but both of these are implied by the act of creation and should be the publish.wmo instance's "now".

For subsequent updates, `date_updated` should probably be set by publish.wmo as well, since the update isn't recorded by anything other than the publish.wmo instance.

**Comment by gideonthomas** [comment]
Hmm, I think this should be possible now since we use ISO format which includes the timezone info.

**Comment by Pomax** [comment]
that's probably also worth noting in the docs (somewhere). I've in inserting plain old \*n\*x timestamps

**Comment by gideonthomas** [comment]
We should also change all the date fields to actual datetime sql types.

**Comment by Pomax** [comment]
:+1:
