### ISSUE TITLE
Implement PUT /projects/:username/:projectname/rename w/ tests

### ISSUE THREAD

**Issue by sedge** [mozilla/publish.webmaker.org#19]
This route is meant to simplify the rename operation into one API call to support users with spotty internet connections.

**Comment by gideonthomas** [comment]
We might not need this route any more since we now key with IDs.
So, we can just send a PUT /users/:userID/projects/:projectID with a message body like so:
```javascript
{
   id: ...,
   name: <newName>,
   <other project metadata>
}
```

**Comment by ashleygwilliams** [comment]
p sure i agree with @gideonthomas but i may be forgetting the nuance we discussed when we came up with this during our Friday convo. @sedge do you remember at all?
