### ISSUE TITLE
Cache id info so we don't need to hit id.mozilla.org so often

### ISSUE THREAD

**Issue by humphd** [mozilla/publish.webmaker.org#194]
From https://github.com/mozilla/thimble.webmaker.org/issues/1225#issuecomment-155141733:

<blockquote>
We might want to consider storing "sessions" on publish (probably as a table or by extending the "users" table with a mapping of username/id to "current oauth token") so that we only hit id.wm.org once and hit our local db instead for routes that require authz every time and are used often (like the PUT routes). I know this sorta defeats the oauth paradigm but this might give us some considerable savings wrt response times.
</blockquote>

Maybe do it with redis instead of adding a new table, and just keep the expiry time on the key somewhat short.

cc @cadecairos, @jbuck .

**Comment by humphd** [comment]
Overnight we got crushed on publish production with timeouts, even after all the changes we made to Thimble on the client side to reduce this.  The real problem is that id.webmaker.org was taking, on *average*, ~8s (that's s, not ms!):

![screenshot 2015-11-16 11 13 44](https://cloud.githubusercontent.com/assets/427398/11187146/3ea7db7c-8c53-11e5-8f96-2e2339e4d815.png)

I spoke with @cadecairos and @jbuck, and asked about the status of https://github.com/mozilla/id.webmaker.org/pull/403, which will hopefully fix this long term.  They said that landing this will require switching the rest of the apps that have dependencies on login.webmaker.org off of it--I don't expect this will be quick.  Jon agreed that we should explore some kind of caching solution in publish in the meantime.

As a result, I want to see us prioritize this.  @jbuck, @cadecairos if you have any suggestions or ideas on what we should do here, let us know.

**Comment by jbuck** [comment]
You could do something like taking the output of the get user call, encrypting the bits you need with [iron](https://www.npmjs.com/package/iron), then sending that encrypted token back to the client. Then the client could send that encrypted token to the publish server instead of sending the oauth token.

**Comment by gideonthomas** [comment]
I don't think this is really necessary for a while. We should just monitor the traffic and see if this is still a major issue. Otherwise we should just rely on the fact that the login.wm.org dep is going to be cut off soon which should make id.wm.org faster.

**Comment by humphd** [comment]
Agree, I would not do this.  Adding yet another caching layer doesn't seem smart to me; also, the metrics on Publish Prod are really steady these days.
