### ISSUE TITLE
Implement PUT /projects/:username/:projectname/files/:filename/rename w/ tests

### ISSUE THREAD

**Issue by sedge** [mozilla/publish.webmaker.org#20]
This route simplifies the process of renaming a file by reducing it to a single API call.

**Comment by gideonthomas** [comment]
We might not need this route any more since we now key with IDs.
So, we can just send a PUT /users/:userID/projects/:projectID/files/:fileID with a message body like so:
```javascript
{
   id: ...,
   name: <newName>,
   path: <updated path>
   <other file data>
}
```

**Comment by gideonthomas** [comment]
Renaming a directory might be a bit more complicated though...but I don't think we should worry about that for this heartbeat (maybe we'll deal with this on the client-side)

**Comment by ashleygwilliams** [comment]
:+1: we can just PUT `/file/:id`, no?

renaming a directory would basically be renaming a *bunch* of files
