### ISSUE TITLE
Scaffold task running & testing frameworks

### ISSUE THREAD

**Issue by sedge** [mozilla/publish.webmaker.org#22]
This is a great opportunity to start test coverage of this server.

I'll be aiming to mimic what [api.webmaker.org](http://github.com/mozilla/api.webmaker.org) does, using [lab](https://www.npmjs.com/package/lab) and simple npm scripts for task running.

If we find that task management is getting complicated then we can switch to something like `gulp` or `grunt`.

**Comment by sedge** [comment]
@gideonthomas, @ashleygwilliams, @humphd Any thoughts before I dive in?

**Comment by ashleygwilliams** [comment]
i really prefer using `npm scripts` over gulp or grunt. otherwise, i think trying to conform to decisions already made on api.webmaker.org is :+1:

**Comment by jbuck** [comment]
@ashleygwilliams++ . npm scripts ftw
