### ISSUE TITLE
Allow disabling the remix button

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/publish.webmaker.org#237]
TODO:
- Add a column to the "projects" table that tracks whether the remix button is shown or not (default true)
- Accept a query string parameter for `/publish`. Based on the param, edit the "projects" table.

I think those are the broad strokes of what needs to be done.

@humphd do you think we should completely disable remixing (you can't remix even with the link) based on that toggle or just hide the UI (because that might change the steps above)?

Related: https://github.com/mozilla/thimble.mozilla.org/issues/1623

**Comment by Pomax** [comment]
Don't we already have this in the form of the `readonly` column, used for goggles projects?

**Comment by humphd** [comment]
Oh, it would be nice if we could re-use `readonly`.  @gideonthomas I think our goal is hiding that Remix stuff, I don't think it matters how we do it.

**Comment by gideonthomas** [comment]
Nice catch @Pomax! Totally forgot about that! I think only the second step needs to be done in that case. And yeah, let's just hide the remix button instead of disabling it completely (since it's easier).
