### ISSUE TITLE
Implement oauth2 resource provider authentication

### ISSUE THREAD

**Issue by sedge** [mozilla/publish.webmaker.org#28]
The `publish.wm.o` server will be acting as an [oauth2 resource server](https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2), so we need to teach it how to validate oauth tokens against `id.wm.o`

**Comment by sedge** [comment]
From our discussions, here's how this will work (using thimble as an example):

*  A user signs into thimble, getting an `oauth` token from `id.wm.o`. After this, but before returning anything to the client, thimble will check if a `publish.wm.o` user exists by hitting GET `/user`, passing a unique, secure identifier provided by `id.wm.o`. If the user doesn't exist (returns 404), thimble will create it with POST `/user`.
*  Each subsequent request from `thimble.wm.o` to `publish.wm.o` will include the user's unique, secure identifier to tell `publish.wm.o` who is trying to modify a resource. 
*  If the identifier matches the owner of the *protected* resource, as stored in `publish.wm.o`'s user table and as a foreign key in the resource's table entry, `publish.wm.o` allows the operation.

@simonwex @cadecairos Can we make this happen? Would the user_id that `id.wm.o` is aware of fit the bill for a unique secure identifier? If not, `id.wm.o` will have to generate one for each user.

**Comment by sedge** [comment]
In case I didn't make it clear, in this world the browser would never communicate directly with `publish.wm.o`.

**Comment by ashleygwilliams** [comment]
@sedge thimble will def be making requests to `publish.wm.o`. i'm not sure we're on the same page...

**Comment by sedge** [comment]
I never clarified here - the thimble server will communicate with `publish.wm.o` on the user's behalf, exposing a separate API for use with the thimble client library @gideonthomas is developing.

**Comment by sedge** [comment]
From 56:

*POST, PUT, DELETE projects, files only for the user that owns it
GET projects only for projects that are isPublic=true for non-owner users*
