### ISSUE TITLE
 Update data models to reflect the Teach team's requirements

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/publish.webmaker.org#29]
Our data models need to evolve to identically map the UX workflow and representation of data on Thimble's side.

One of the recent changes that we discussed is to add a `tags` attribute to the projects model to store project-related tags that a user might specify. Another change was to add a `description` attribute to the project as well.

We probably eventually want to include thumbnails as well for projects depending on how the UX team decides to implement thumbnails.

**Comment by ashleygwilliams** [comment]
good note. is this a complete list? i can add this now.

**Comment by gideonthomas** [comment]
It isn't a complete list, but for now, I think we should just add `tags` and `description`

**Comment by gideonthomas** [comment]
Actually, a couple of other fields I remember that need to be added to the `Projects` model are:
* `dateCreated`
* `dateLastModified`

**Comment by ashleygwilliams** [comment]
how about `date_updated`

**Comment by gideonthomas** [comment]
sure
