### ISSUE TITLE
[META] Create sequence diagrams for publish systems

### ISSUE THREAD

**Issue by sedge** [mozilla/publish.webmaker.org#4]
We need diagrams for creation, updating, publishing, unpublishing, deleting and renaming projects.

**Comment by ashleygwilliams** [comment]
@gideonthomas shared these in irc today:

![screenshot 2015-06-09 at 6 51 34 pm](https://cloud.githubusercontent.com/assets/1163554/8071495/98f87350-0ed8-11e5-9a80-c581d2c28f52.png)
![screenshot 2015-06-09 at 6 51 25 pm](https://cloud.githubusercontent.com/assets/1163554/8071496/9c14c69c-0ed8-11e5-8bbf-26610d7fe54a.png)

**Comment by gideonthomas** [comment]
Updated diagrams:
**Open thimble and sign in**
![workflow_1](https://cloud.githubusercontent.com/assets/5816130/8085797/fc298cf2-0f5f-11e5-88ce-1abe748d18bb.png)
**Open project**
![workflow_2](https://cloud.githubusercontent.com/assets/5816130/8085816/24946f68-0f60-11e5-98b3-26b79c840385.png)

**Comment by ashleygwilliams** [comment]
hey @gideonthomas do you want to place the "finals" of these in a spot on the wiki? might be easier for people hwo are trying to consume them

**Comment by gideonthomas** [comment]
yeah absolutely!

**Comment by sedge** [comment]
This seems to be frozen for now. Closing...
