### ISSUE TITLE
Allow generic configuration of project metadata

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/publish.webmaker.org#48]
I think we want to have a way to store arbitrary metadata about a project. One use case for this is [here](https://github.com/mozilla/thimble.webmaker.org/issues/549#issuecomment-110506843), where Thimble wants to be able to store the last line edited in a project (brackets requires some config data to highlight the line in the editor).

To make this 'client-agnostic', can we maybe add a field to the projects table (maybe "meta" or something)? I don't really know how we want to store this data? Maybe as a string with JSON formatting like:
```js
{
  "thimble" : {
    "meta1": ...,
    "meta2": ...,
    ...
  }
}
```
And then have special routes that deal with providing this data? (only provide app-specific metadata i.e. thimble should not be able to get goggles' metadata)

Just throwing some ideas around, but I have no idea how we should implement this. 
**But this is def not MVP!**

@ashleygwilliams thoughts?

**Comment by ashleygwilliams** [comment]
related #159
