### ISSUE TITLE
Implement test coverage

### ISSUE THREAD

**Issue by sedge** [mozilla/publish.webmaker.org#49]
We have test scaffolds, but no relevant tests.

**Comment by sedge** [comment]
@cadecairos @jbuck @simonwex Tests always bring up the issue of response design. Can we make up the format of the response body? Or would you prefer something standardized, like [json-api](http://jsonapi.org/format/)?

**Comment by ashleygwilliams** [comment]
i vote for json-api. see: https://github.com/mozilla/api.webmaker.org/issues/80

**Comment by sedge** [comment]
Fixed in #58 & #65. closing
