### ISSUE TITLE
Don't send file data through JSON

### ISSUE THREAD

**Issue by ashleygwilliams** [mozilla/publish.webmaker.org#52]
otherwise we end up encoding/decode the buffer

here's a npm package to use: https://www.npmjs.com/package/protobufjs
here's why we should use it: http://blog.codeclimate.com/blog/2014/06/05/choose-protocol-buffers/

**Comment by sedge** [comment]
We're going to be using `form/multi-part` to accomplish this. PR in #119

**Comment by gideonthomas** [comment]
Going to close this for now since we're streaming to publish using form-data and streaming from publish using tarballs. We still have the json routes but we never use them.
