### ISSUE TITLE
Should file paths be absolute

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/publish.webmaker.org#60]
The seed files have hardcoded paths for the file objects which are relative i.e. `index.js` vs. `/myproject/index.js`. We should change it so that it is easy to test on the client (with these default values).

This brings up another issue about how we should store file paths. I think they always should be absolute   so that they can be used *as is* when it reaches the client (I don't think we want the client to path-scope files). For e.g. if I get a file using `GET /files/4`, I get a relative path and a project_id...now to construct a proper path, I have to send another request `GET /projects/project_id` just to get the name and append it to my file paths. I'm not sure it makes sense to force the client to make an extra unnecessary request.

In the case of renames, we have two ways we can implement this. We can either update the file paths on renaming a project on the server (this means saying `PUT /projects/1` updates the project and everything that relies on it) or we can offload this to the client (since the client should have its own renaming logic). Either way should be completely fine

**Comment by ashleygwilliams** [comment]
if you use `projects/1?include=files` you get the project and file data in a single request. this landed yesterday. #61

**Comment by gideonthomas** [comment]
Closing this issue since we're going with absolute paths without the project name because we need to prepend those paths in thimble with custom paths.
