### ISSUE TITLE
Deploy `publish` to staging

### ISSUE THREAD

**Issue by sedge** [mozilla/publish.webmaker.org#73]
We're about at the point where a staging server would be great to have. We already have a heroku instance set up, so maybe we could use that?

@jbuck What do we need to do for this?

**Comment by ashleygwilliams** [comment]
i have already transferred the heroku instance to the mozilla org on heroku

**Comment by jbuck** [comment]
If you've already got it running on Heroku it sounds like you're done

**Comment by sedge** [comment]
@jbuck Don't we want it running on a staging domain somewhere?

**Comment by jbuck** [comment]
What's the Heroku app URL? I can't find it in the apps list.

**Comment by ashleygwilliams** [comment]
https://damp-anchorage-2948.herokuapp.com/ (also lives in the desc of this repo :wink:  )

**Comment by ashleygwilliams** [comment]
![screen shot 2015-06-19 at 10 26 29 am](https://cloud.githubusercontent.com/assets/1163554/8255391/ae7b6a4c-166d-11e5-8e44-fcbf49a69104.png)
