### ISSUE TITLE
#76: create doesn't respect `id` increments

### ISSUE THREAD

**Issue by ashleygwilliams** [mozilla/publish.webmaker.org#77]
CLIENT:
```
$ curl -X POST --data "name=poop" http://localhost:2015/users
{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}
```

SERVER:
```
[2015-06-18T04:22:57.246Z] ERROR: publish.webmaker.org/67140
on Ashleys-MacBook-Pro.local: insert into "users" ("name") values
($1) returning "id" - duplicate key value violates unique constraint "users_pkey"
```

on a subsequent `POST` the `id` increments, eventually works once the `id` > 3 (after 3 tries)

**Comment by sedge** [comment]
Bookshelf threw the following error message (along with other data): `"insert into "users" ("name") values ($1) returning "id" - duplicate key value violates unique constraint "users_pkey""`

Do we have a constraint on `name` forcing it to be unique?

**Comment by sedge** [comment]
I see now there's not much new to go off of here. I'll dig into the error object a little more.

**Comment by sedge** [comment]
@ashleygwilliams At least for the user, I know what the problem is. The seeds declare the ids for the first three users manually, which must not be auto-incrementing the counter in the DB. I'll throw up a PR for that.
