### ISSUE TITLE
GET /users?username=??? should create a user if it doesn't exist

### ISSUE THREAD

**Issue by sedge** [mozilla/publish.webmaker.org#80]
This functionality doesn't work as far as I know.

**Comment by ashleygwilliams** [comment]
i've been thinking about this a lot and i think it might be nicer as a RPC `POST /users/login` that passes a `payload` with the `name`. if the user exists, return it, if the user doesn't exist, create it and then return it.

`GET` requests can be cached and i don't think we want that.

say the word and i'll implement it.

**Comment by sedge** [comment]
Let's do it.

**Comment by gideonthomas** [comment]
yeah that sounds good!

**Comment by gideonthomas** [comment]
@ashleygwilliams If you can prioritize this fix that would be great coz it's blocking me.

**Comment by ashleygwilliams** [comment]
ok. on it.

**Comment by ashleygwilliams** [comment]
solved.
