### ISSUE TITLE
Update operations should return 200 if no data was changed

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/publish.webmaker.org#94]
https://github.com/mozilla/publish.webmaker.org/blob/master/api/classes/base_controller.js#L58 is not a good idea. It makes it really hard for the client to differentiate between "The id I sent does not reference an existing resource" and "The data I sent had no real effect". The second case doesn't really imply an error case so a 404 might not be a good way to deal with it.

**Comment by ashleygwilliams** [comment]
what would you prefer

**Comment by sedge** [comment]
As long as it's distinguishable I'm not sure it matters. I'm going to say `200` for "no real effect" case.

**Comment by ashleygwilliams** [comment]
this would throw when the database fails to update the resource- 200 seems wrong. how about http://www.checkupdown.com/status/E304.html

**Comment by sedge** [comment]
Sure!

**Comment by gideonthomas** [comment]
We should consider what the upside would be to sending back a 304 vs. the following:

We change the file resource to include a `date_updated` attribute which means that the client will always have a different representation everytime we send a request to the `/files/{id}` route (because the client will update the `date_updated` attribute). This way we can keep the 404 case as is. We might also want to add logic to the route so that publish will update the project's `date_updated` accordingly as well (OR we can offload this to the client).

Just something to consider!

cc @sedge, @ashleygwilliams

**Comment by ashleygwilliams** [comment]
the timestamps should have a single source of truth, either the client or server. we have already decided that the client is that, so i think we should keep that.

if we change it, we should force the source of truth to be the server on all fronts. generally speaking, i do think the database/server should be doing the timestamps as that is when the stuff is actually *real*, i.e. persisted, but i'm happy to leave this up to ya'll.

**Comment by sedge** [comment]
Re: source of truth. Let's make it the client - we've gone in that direction already so let's follow it through.

Re: 304 vs timestamp. The answer is we still need the 304, because publish can't guarantee that the client will send a new `date_updated`. In this case, the 304 might be enough.
