### ISSUE TITLE
Support the remix workflow in publish.webmaker.org

### ISSUE THREAD

**Issue by sedge** [mozilla/publish.webmaker.org#97]
To support remixing other published projects we need to enable the workflow in two ways:

* [x] Instrumenting "Remix" code into any project as it is being published
* [x] Caching the non-instrumented version of a published project while it's being published, and updating that cached version whenever a project is republished
* [x] Adding a route for getting the published version of another user's project.

**Comment by gideonthomas** [comment]
Fixed in 13d35e1e82dd8453d9c85332d83c21b5264615af and 2b1ed7d44516d7e46d858ca26fa6a16f570e3ebc
