### ISSUE TITLE
Have a `public` property on the projects resource

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/publish.webmaker.org#98]
We need a way to tell if a published project is discoverable publicly or not. I think the way to do this is to have a `public` field in the database that indicates this.

**Comment by sedge** [comment]
Once #96 lands I can add that in pretty easily.

**Comment by gideonthomas** [comment]
Waiting on UX decisions on thimble for this to be implemented. This is definitely not part of MVP

**Comment by ashleygwilliams** [comment]
adding the field doesn't necessarily need to wait on UX- thoughts?

related: #48 #159

**Comment by gideonthomas** [comment]
We might not want to add this field until they decide that they absolutely need it (which as of right now, they don't)
